
language: python
sudo: false

services:
  - mongodb

##### start programmatically generated python section #####
python:
  - 2.7
  - 3.4
##### end programmatically generated python section #####

##### start programmatically generated env section #####
env:
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=v0.1.0 BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=master FILESTORE=v0.1.0 BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=master BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=master FILESTORE=master BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=v0.1.0 BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=master FILESTORE=v0.1.0 BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=master BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=master FILESTORE=master BLUESKY=v0.1.0 REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=v0.1.0 BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=master FILESTORE=v0.1.0 BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=master BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=v0.1.0 SKXRAY=master METADATASTORE=master FILESTORE=master BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=v0.1.0 BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=master FILESTORE=v0.1.0 BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=v0.1.0 FILESTORE=master BLUESKY=master REPLAY=master SUITCASE=master
  - DATAPORTAL=master SKXRAY=master METADATASTORE=master FILESTORE=master BLUESKY=master REPLAY=master SUITCASE=master
##### end programmatically generated env section #####

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  # next 3 lines are needed to spawn a GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 1920x1080x32"
  # Set up config for MDS
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  # Set up config for FS
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda create -n testenv --yes pip nose python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy pandas scikit-image h5py matplotlib jsonschema coverage
  # Dependencies not in official conda have been uploaded to binstar orgs.
  - source activate testenv
  - conda install --yes -c soft-matter pims tifffile
  - conda install --yes -c nikea mongoengine
  - conda install --yes -c lightsource2 epics-base readline lmfit prettytable pcaspy
  - conda install --yes -c tacaswell cycler xraylib
  - 'pip install https://github.com/NSLS-II/channelarchiver/zipball/master#egg=channelarchiver'
  # scikit-xray
  # dataportal
  - pip install humanize boltons
  # python 3 deps only
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then

        conda install --yes -c lightsource2 super_state_machine;
    fi;
g  - cd ..
  ###### start programmatically generated repo clone/install ######
  - git clone https://github.com/NSLS-II/dataportal
  - cd dataportal
  - git checkout $DATAPORTAL
  - python setup.py develop
  - cd ..
  - git clone https://github.com/NSLS-II/metadatastore
  - cd metadatastore
  - git checkout $METADATASTORE
  - python setup.py develop
  - cd ..
  - git clone https://github.com/NSLS-II/filestore
  - cd filestore
  - git checkout $FILESTORE
  - python setup.py develop
  - cd ..
  - git clone https://github.com/NSLS-II/bluesky
  - cd bluesky
  - git checkout $BLUESKY
  - python setup.py develop
  - cd ..
  - git clone https://github.com/NSLS-II/replay
  - cd replay
  - git checkout $REPLAY
  - python setup.py develop
  - cd ..
  - git clone https://github.com/NSLS-II/suitcase
  - cd suitcase
  - git checkout $SUITCASE
  - python setup.py develop
  - cd ..
  - git clone https://github.com/scikit-xray/scikit-xray
  - cd scikit-xray
  - git checkout $SKXRAY
  - python setup.py develop
  - cd ..
  ###### stop programmatically generated repo clone/install ######
  - cd vertical-integration
script:
  - echo "debug info"
  - conda list
  ##### start programmatically generated test running script #####
  - cd dataportal;
  - python run_tests.py;
  - cd ..;
  - cd filestore;
  - python run_tests.py;
  - cd ..;
  - cd metadatastore;
  - python run_tests.py;
  - cd ..;
  - cd scikit-xray;
  - python run_tests.py;
  - cd ..;
  - cd suitcase;
  - python run_tests.py;
  - cd ..;
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then
        cd bluesky;
        python run_tests.py;
        cd ..;
    fi;
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" ]; then
        cd replay;
        python run_tests.py;
        cd ..;
    fi;
  ##### stop programmatically generated test running script #####
